### ISSUE TITLE
App clear canvas while change from portrait to landscape 

### ISSUE THREAD

**Issue by darewealth** [zahid-ali-shah/SignatureView#14]
EXPECTED BEHAVIOR
The app was not expected to clear canvas whether portrait or landscape 

ACTUAL BEHAVIOR
When i change from portrait to landscape the signature clear

HOW TO REPRODUCE

Launch the app and open

Sigh anythings on the app 

Change to landscape and note the bug

Device used: Tecno Droipad 7D

Operating system: Android version 7.0

App version: 1.0.2

Recording of the Bug
https://youtu.be/5NKPOKmmmVg

**Comment by eriknyk** [comment]
+1

can we merge the fix to rotation fix?
