### ISSUE TITLE
Download icon didn't work 

### ISSUE THREAD

**Issue by darewealth** [zahid-ali-shah/SignatureView#15]
EXPECTED BEHAVIOR
The app was expected to download signature when clicked on the icon.

ACTUAL BEHAVIOR
when clicked on download icon option it didn't work

HOW TO REPRODUCE

Launch the app and open

Sigh anythings on the app

Click download icon at the top and note the bug

Device used: Tecno Droipad 7D

Operating system: Android version 7.0

App version: 1.0.2

Recording of the Bug

https://youtu.be/cr6WfikcnW8

**Comment by zahid-ali-shah** [comment]
Sorry, this repo is no longer maintained
