### ISSUE TITLE
Render a bitmap in Signature View.

### ISSUE THREAD

**Issue by DhanalakshmiS** [zahid-ali-shah/SignatureView#3]
I am able to capture signature and get a bitmap of the signature.But there are no options to render a bitmap into Signature View.
I tried using ,
 signatureView.draw(new Canvas(bitmap));

But it didn't work out.

I have fixed the bug and have opened a pull request.If you are ok with it you can merge it.

**Comment by zahid-ali-shah** [comment]
Fixed in pull request #5
